---
- name: Configure Flathub for the target user
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: user
  become: "{{ ansible_user_id != target_user }}"
  become_user: "{{ target_user }}"
  environment:
    HOME: "{{ target_home }}"
  when: fedora44_install_protonplus | bool

- name: Install ProtonPlus for the target user
  community.general.flatpak:
    name: com.vysp3r.ProtonPlus
    state: present
    remote: flathub
    method: user
  become: "{{ ansible_user_id != target_user }}"
  become_user: "{{ target_user }}"
  environment:
    HOME: "{{ target_home }}"
  when: fedora44_install_protonplus | bool
