---
- name: Configure Docker system components
  ansible.builtin.include_tasks:
    file: system.yml
    apply:
      tags:
        - system
  tags:
    - system

- name: Configure Docker user access
  ansible.builtin.include_tasks:
    file: user.yml
    apply:
      tags:
        - user
  tags:
    - user
