---
- name: Install zsh environment packages on Fedora
  ansible.builtin.dnf:
    name:
      - zsh
      - git
      - zoxide
      - direnv
      - wl-clipboard
    state: present
  become: true
  when: ansible_distribution == 'Fedora'
  tags:
    - system
    - zsh
