---
- name: Configure Fcitx system packages
  ansible.builtin.include_tasks:
    file: system.yml
    apply:
      tags:
        - system
  tags:
    - system

- name: Configure the target user's Fcitx environment
  ansible.builtin.include_tasks:
    file: user.yml
    apply:
      tags:
        - user
  tags:
    - user
