---
- name: Install k3s (single node)
  ansible.builtin.shell: curl -sfL https://get.k3s.io | sh -
  args:
    creates: /usr/local/bin/k3s
  become: true
  when: ansible_facts['system'] != 'Darwin'

- name: Ensure .kube directory exists
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.kube"
    state: directory
    owner: "{{ ansible_facts['user_id'] }}"
    mode: "0700"
  when: ansible_facts['system'] != 'Darwin'

- name: Copy kubeconfig to user home
  ansible.builtin.copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "{{ ansible_facts['user_dir'] }}/.kube/config"
    remote_src: true
    owner: "{{ ansible_facts['user_id'] }}"
    mode: "0600"
  become: true
  when: ansible_facts['system'] != 'Darwin'
