---
fedora44_install_cli_tools: true
fedora44_install_heavy_debug_tools: true
fedora44_install_hardware_cli_tools: true

fedora44_cli_core_packages:
  - bat
  - btop
  - entr
  - fd-find
  - hyperfine
  - jq
  - lsof
  - ripgrep
  - sysstat
  - tealdeer
  - tmux

fedora44_cli_network_packages:
  - bind-utils
  - ethtool
  - iperf3
  - mtr
  - nmap-ncat
  - tcpdump

fedora44_cli_hardware_packages:
  - lm_sensors
  - nvme-cli
  - pciutils
  - smartmontools
  - usbutils

fedora44_cli_debug_packages:
  - gdb
  - perf
  - strace
  - valgrind
