---
- name: Download helm install script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: "0700"
  when: ansible_facts['system'] != 'Darwin'

- name: Run helm install script
  ansible.builtin.command: /tmp/get_helm.sh
  args:
    creates: /usr/local/bin/helm
  become: true
  when: ansible_facts['system'] != 'Darwin'

- name: Install helm via Homebrew on macOS
  ansible.builtin.include_tasks:
    file: mac.yml
  when: ansible_facts['system'] == 'Darwin'
